name: GHTranscribe
options:
  bundleIdPrefix: com.guyharrison
  deploymentTarget:
    iOS: "17.0"
  createIntermediateGroups: true
targets:
  GHTranscribe:
    type: application
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - path: GHTranscribe
    configFiles:
      Debug: Local.xcconfig
      Release: Local.xcconfig
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.guyharrison.ghtranscribe
        PRODUCT_NAME: GHTranscribe
        SWIFT_VERSION: 5.0
        TARGETED_DEVICE_FAMILY: "1"
        GENERATE_INFOPLIST_FILE: YES
        INFOPLIST_KEY_UILaunchScreen_Generation: YES
        INFOPLIST_KEY_CFBundleDisplayName: GHTranscribe
        INFOPLIST_KEY_UISupportedInterfaceOrientations: UIInterfaceOrientationPortrait
        CODE_SIGN_STYLE: Automatic
